from __future__ import annotations

from agentlens import (
    database_core,
    experiment_repository,
    review_repository,
    tool_grant_repository,
)

EXPECTED_SCHEMA_REVISION = database_core.EXPECTED_SCHEMA_REVISION

# Stable compatibility facade for integrations that still import agentlens.database.
_as_utc = database_core.as_utc
_database_lock = database_core.database_lock
engine = database_core.engine
init_database = database_core.init_database
schema_revision = database_core.schema_revision
session_factory = database_core.session_factory
sessions = database_core.sessions

_execution_payload = experiment_repository.execution_payload
_summary_from_record = experiment_repository.summary_from_record
claim_experiment = experiment_repository.claim_experiment
compare_and_set_status = experiment_repository.compare_and_set_status
latest_persisted_experiment = experiment_repository.latest_persisted_experiment
list_persisted_experiments = experiment_repository.list_persisted_experiments
load_execution_state = experiment_repository.load_execution_state
load_experiment = experiment_repository.load_experiment
mark_experiment_cancelled = experiment_repository.mark_experiment_cancelled
mark_experiment_failed = experiment_repository.mark_experiment_failed
mark_stale_experiment = experiment_repository.mark_stale_experiment
mark_stale_experiments = experiment_repository.mark_stale_experiments
persist_experiment = experiment_repository.persist_experiment
persist_queued_experiment = experiment_repository.persist_queued_experiment
persisted_counts = experiment_repository.persisted_counts
update_experiment_progress = experiment_repository.update_experiment_progress
update_experiment_status = experiment_repository.update_experiment_status

FailureReviewClaim = review_repository.FailureReviewClaim
claim_failure_review = review_repository.claim_failure_review
persist_failure_review = review_repository.persist_failure_review
release_failure_review_claim = review_repository.release_failure_review_claim

consume_tool_grant = tool_grant_repository.consume_tool_grant
issue_tool_grant = tool_grant_repository.issue_tool_grant
maintain_tool_grants = tool_grant_repository.maintain_tool_grants
revoke_tool_grant = tool_grant_repository.revoke_tool_grant
tool_grant_token_hash = tool_grant_repository.tool_grant_token_hash
